//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:31:17 PM IST 
//


package com.fenintechnologies.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fenintechnologies.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fenintechnologies.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfBA }
     * 
     */
    public ArrayOfBA createArrayOfBA() {
        return new ArrayOfBA();
    }

    /**
     * Create an instance of {@link ArrayOfBA.BA }
     * 
     */
    public ArrayOfBA.BA createArrayOfBABA() {
        return new ArrayOfBA.BA();
    }

    /**
     * Create an instance of {@link ArrayOfBA.BA.SSS }
     * 
     */
    public ArrayOfBA.BA.SSS createArrayOfBABASSS() {
        return new ArrayOfBA.BA.SSS();
    }

    /**
     * Create an instance of {@link ArrayOfBA.BA.SCSS }
     * 
     */
    public ArrayOfBA.BA.SCSS createArrayOfBABASCSS() {
        return new ArrayOfBA.BA.SCSS();
    }

    /**
     * Create an instance of {@link ArrayOfBA.BA.PSS }
     * 
     */
    public ArrayOfBA.BA.PSS createArrayOfBABAPSS() {
        return new ArrayOfBA.BA.PSS();
    }

}
